### ISSUE TITLE
Stuck on "loading..." 

### ISSUE THREAD

**Issue by MakuraYami** [simonvizzini/vscode-factorio-lua-api-autocomplete#1]
Just tried this extension in most recent version of VSCode (1.12.1) and when I press ctrl+space it just says "loading..." with nothing else.

Also is this updated for 0.15 yet?

Great work on this by the way, it's a really nice idea! :+1:

**Comment by simonvizzini** [comment]
Thanks for reporting! You are right, it's still broken. I released 0.3.1 right after 0.3.0 yesterday because I thought I fixed it. I'll investigate this when I get home tonight.

Every extension update will contain the latest API documentation from http://lua-api.factorio.com/latest/, so it's currently at 0.15.6. I'll add a note regarding this to the readme

**Comment by MakuraYami** [comment]
I just spend a while writing build/watch scripts to make developing easier and not having to keep copying files between factorio-mod-directory and my repository-directory. https://github.com/MakuraYami/factorio-mods You may find the idea useful.

Looking forward to using this extension!

**Comment by simonvizzini** [comment]
I've fixed the bug, will publish it on the marketplace in the next hour.

And thanks for linking your repo! I'll definitively take a look once I actually start to write mods 😄 I'm a lazy programmer so first I need some tools to support my laziness, and a build/watch script is definitively one of those.

**Comment by simonvizzini** [comment]
I just published a new version which should now hopefully work fine. This was totally broken, I naively assumed that the current working directory will be always the path of the extension, but it's actually the path where you open Code. So, my extension probably never worked on anyone's computer except mine :rofl: 

Let me know if it works now for you!

**Comment by MakuraYami** [comment]
Yes it works now, that's pretty nice. Too bad it can't really check types. For example when you do `game.players[x]` that it will know the value is LuaPlayer and autocomplete on it. But it's a nice addition either way, thanks!

**Comment by simonvizzini** [comment]
Glad to hear that!

I'm not really familiar with Lua so I'm not sure if there are IDEs or editor extensions that can keep track of variables and their types. There are a bunch of Lua extensions for Code but I haven't tried them out yet. Do you have any experience regarding Lua editor tooling support?

But anyway, your example would be actually quite easy to realize. I already had it implemented in my initial prototype (before I started to scrape the API docs). It would be just necessary to properly parse dictionary and array types.
For example the `players` type of `LuaGameScript` is defined in data/classes.json as:
`"type": "custom dictionary uint or string → LuaPlayer"`

Other examples:
````
"type": "custom dictionary string → ModSetting"
"type": "dictionary string → LuaItemPrototype"
"type": "array of LuaEquipment"
````

I guess the easiest approach would be to parse all these types as `LuaPlayer[]` or `LuaEquipment[]` etc, then it would be possible to provide autocompletion for `game.players[x]`

**Comment by MakuraYami** [comment]
Sorry I have no experience with IDE extensions or support like this. I'm more into the node scripts and I can manage writing mods in Lua. Sounds like you do have a solution in mind, it would be nice if that was supported. Good luck with it though 👍
