### ISSUE TITLE
Update to latest Factorio version

### ISSUE THREAD

**Issue by realvictorprm** [simonvizzini/vscode-factorio-lua-api-autocomplete#2]
Right now this is outdated for the latest Factorio version.

**Comment by simonvizzini** [comment]
Thanks for opening this issue. Sorry that it took so long. I just published version 0.6.0 which includes the API data for Factorio 0.16.51

I'm not sure how often I will be able to update the extension in the future. I'll write down some development documentation and maybe I'll find someone who wants to keep maintaining this extension.

Cheers!

**Comment by realvictorprm** [comment]
Thank you very much, it would be great if you provide more information.
